### ISSUE TITLE
Discuss how the Medical System should work

### ISSUE THREAD

**Issue by jokoho48** [drakelinglabs/projectrealityarma3#11]

**Comment by simon84** [comment]
Since we wanted to have a vanilla based medical System, we veed to use vanilla items. My idea is the following.

- If a player is shot and a critical damage value is exceeded, the player Begins to bleed.
- Every soldier is capable of using First Aid Kits to stop bleeding, but not restoring health.
- Every Medic can use a First Aid Kit (or MediKit) to restore health to 100%.
- If blood or health falls under a certain value, the player falls into unconscious.
- Every soldier can restore health of an unconscious player above the unconscious threashold.

Hopyfully you understand my ideas.

**Comment by netfusion** [comment]
My idea is:
- Make the FAK like a Bandage to stop bleeding
- Make the Medikit (medic only) able to revive play from unconsciousness

**Comment by Bluedrake42** [comment]
We should not focus on having any item be restricted for any class. We
should make sure all classes can use every item, but perhaps certain
classes have certain perks that allow them to use those items better. For
instance all players can revive a player, all players can use a medikit to
stabilize a player, but only medics can use a medikit to heal a player to
full health.

Making sure we keep these kinds of things in mind is what is going to help
make ArmA's complex inventory system work nicely with our style of
gameplay. Keep in mind we're making PR:A3, not PR.

**Comment by simon84** [comment]
In vanilla, the medkit is restricted to the medic.

**Comment by Bluedrake42** [comment]
The last thing we used was End Game, in End Game the medic/revive system
allows all players to revive, but anyone with a medkit to revive in half
the time.

On Fri, Mar 4, 2016 at 1:53 AM, BadGuy <notifications@github.com> wrote:

> In vanilla, the medkit is restricted to the medic.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/drakelinglabs/projectrealityarma3/issues/11#issuecomment-192142817>
> .
>



-- 
Sincerely,
Connor Hill (Bluedrake42)
Cellphone: 502-804-6438
ConnorDHill@Gmail.com

**Comment by Hoegnison** [comment]
IMO the last Medic System as Bluedrake discriped, worked out very well in our playtest. In ArmA it is easy to die in easy to loose your medic somwhere in the woods. For the first prototypes and playtests I would defenitly stick to the old system. Than we have to work with the feedback of the community I think.
