### ISSUE TITLE
Macro cleanup

### ISSUE THREAD

**Issue by netfusion** [drakelinglabs/projectrealityarma3#33]
Remove:
* EGVAR, QEGVAR -> creates untracked dependencies, use events instead
* EFUNC, QEFUNC -> same as above
* DFUNC -> can be replaced with GVAR, functions should be declared in their own file

Add:
* UIVAR(var) -> QUOTE(PRA3_UI_##var), afaik all ui stuff require strings only so no unquoted version is needed

**Comment by simon84** [comment]
I understand your complains about the modularity. But we have to keep in mind, that  we are not building a mission framework which is capable of building a varios type of tvt modes. Using events for simple tasks like propagating the ticket values, is possible and clean in a design point of view, but in my opinion much more demanding in performance and network traffic. Additional to this example, which in my opinion is speaking for using global variables, external global functions are also necessary in terms of performance optimization, due to a lower overhead. (show Notification function). So thats my opinion in a special view on the project here. In general, I like the idea of putting away this shit!

**Comment by netfusion** [comment]
There are still ways to use external global functions. If module a needs to call a function in module b for example:
* group a and b as submodules of c
* move function of module b to core

The showNotification function is in my opinion part of the core.

**Comment by simon84** [comment]
Ok, I see the point. I have to think ...

**Comment by simon84** [comment]
Ok. I'm not against it :)

**Comment by jokoho48** [comment]
i am against removeing DFUNC because its curretly the only way to define a function in without a new file and GVAR is there more bulky from my point of view

**Comment by netfusion** [comment]
Just to quote the ACE guidelines (which you should know)...

"All functions shall be put in their own .sqf file."
http://ace3mod.com/wiki/development/coding-guidelines.html#own-sqf-file

Two liners which are somewhere defined between the files are hard to locate and even harder to maintain. Nobody guarantees that they will stay the same size all time.

**Comment by jokoho48** [comment]
UIVAR added
