### ISSUE TITLE
Write Medical System NOW

### ISSUE THREAD

**Issue by jokoho48** [drakelinglabs/projectrealityarma3#41]
The Vanilla System is so Buggy and Fucked

**Comment by simon84** [comment]
We have a problem in disabling the vanilla "Treat". As far as I know, we cannot disable or rename this action. As long as a unit has a FAK of Medkit. This action is visible. My first guess was to use the "HandleHeal" event for bandaging, but since the "Treat" action cannot be renamed, it's very confusing to the player, when he has a "Treat" (which means bandage) and a "Heal" action. Do you have any ideas how to face this problem. Maybe we have to simplify the system in the following way:

We use only first aid kits, which are able to bandage and heal a unit. This could result in one single "Treat" action.

**Comment by netfusion** [comment]
We could disable the vanilla action system with `showHUD` command.
This requires rewriting all other actions though.

**Comment by simon84** [comment]
So, we need to rewrite a completly new Action System? Hmmm ... Why not :)! The vanilla system sucks :)

**Comment by jokoho48** [comment]
- [ ] fix switchMove bug (@me)
- [ ] write Loadingbar to show the Uncon player how long he will survive/time to bleedout ( @simon84 )
- [ ] save progress in healing! ( @simon84 )

**Comment by jokoho48** [comment]
Current Flow idea for Revive System
http://puu.sh/nPJjH/9900d43403.png

**Comment by simon84** [comment]
Simultaneous Healing is finished - needs testing

**Comment by jokoho48** [comment]
Split up in smaller tasks
